### PR TITLE
ODT refactoring

### PR DESCRIPTION
**Pull request by selfthinker**
Latest changes from @LarsGit223's fork.
Continuation of #103.

### CODE REVIEW

**Comment by selfthinker** [comment]
Without knowing what most of the ODT-related stuff does, this definitely looks much cleaner than before! :)

**Comment by selfthinker** [comment]
I noticed that the table at the top of the example document (the one with the three columns) is now narrower than before. But I believe that was already the case with the currently merged version, but only after I updated the ODT plugin. So, it's probably something which was introduced in the recent changes of the ODT plugin?

**Comment by LarsGit223** [comment]
Yes, some things on the X axis are now smaller since the "twips per pixel" option has been built-in.

**Comment by selfthinker** [comment]
Any news on this?

**Comment by LarsGit223** [comment]
Well, as you see the mergae is done.

Regarding the CSS I found out the following:
- for some reason, `@import` does not import `.css` files. There is a check in css.php which explicitly aborts an import if the file has an `.css` extension
- if I change the file extension and import style.css the following problems occur:
  - normal style and print style is mixed up
  - URLs for images are not correctly expanded to the local path (the part `plugins/wrap` is missing. This doesn't happen if the code has just been copied to the file.

So I decided to try to not use `odt.css` at all for wrap and tried a configuration with `wrap` listed in the config option `usestyles`.

I found and fixed one issue:
The css import code I have adopted from the `dw2pdf` plugin import the following files if `wrap` is listed in `usestyles`:
- all.css
- style.css
- print.css
(odt.css was deleted as mentioned above)

But the code did not surround print.css with `@media print { ... }`. So I changed my css import code to to that and also sorround `screen.css` with `@media screen { ... }` (if present).

Now, the result of the wrap odt export looks like in the browser, if wrap is listed in `usestyles` and `media_sel` is empty. But there is still an issue: if I set/configure `media_sel` to `print`, then the css properties are mixed up and the boxes e.g. have the backgound-color from style.css and the border-color of print.css.

But fortunately that problem is in my CSS code and so can be fixed without touching css.php.

I was about to read a bit more into the CSS specification about the @media rule but maybe you can help me out also. Of course, I see that the @media print rule overwrites/deletes all properies taken from style.css.

What is the logic behind that? If I have several matching @media rules and/or properties that match ALL like style.css which one has priority? The most specific one?

**Comment by LarsGit223** [comment]
Forget my question:
I just found out that `style.css` is also used for screen media, just like `screen.css`. I thought it's used for media type `all`.

(I was just starting to think I haven't understood the @media rule :-) )

**Comment by selfthinker** [comment]
> for some reason, `@import` does not import .css files. There is a check in css.php which explicitly aborts an import if the file has an .css extension

That cannot be true and would defeat the whole purpose of it. Where in the code do you see that (line number, method name)?

> The css import code I have adopted from the dw2pdf plugin import the following files if wrap is listed in usestyles: all.css, style.css, print.css

That doesn't make any sense, you need to decide if you want to get the print styles (which would include print.css and all.css) or the screen styles (which would include style.css and/or screen.css and all.css).

> But the code did not surround print.css with `@media print { ... }`. So I changed my css import code to do that and also sorround screen.css with `@media screen { ... }` (if present for a plugin).

Why would css for pdf or odt include any `@media` at all? There shouldn't be any distinction between screen and print.

> if I set/configure media_sel to print, then the css properties are mixed up and the boxes e.g. have the backgound-color from style.css and the border-color of print.css.

There shouldn't be anything from style.css in that case.

**Comment by selfthinker** [comment]
> So I decided to try to not use `odt.css` at all for wrap and tried a configuration with `wrap` listed in the config option `usestyles`.

Okay, just tried that and it looks fine.
That means the only thing that needs to be done is to remove `odt.css` and leave a comment about the need to add "wrap" to `usestyles` and then this is ready?

**Comment by selfthinker** [comment]
Instead of merging this, I have cherry-picked and adjusted the two main commits. So, this is in master now.

**Comment by selfthinker** [comment]
I've just done a release. :)
Please feel free to adjust anything I've written here: https://www.dokuwiki.org/plugin:wrap#odt_support

**Comment by LarsGit223** [comment]
Ok, great :-)
Thanks for your help and all the time you put into this. I hope I can implement some of the unsupported things in the future.

The wrap plugin page looks good to me. Only corrected the year in the date (it was 2013-06-13 instead of 2015-06-13).

I will not do a release yet because I still see problems in my CSS import. I did some changes that looked good but now I don't get back any properties from my CSS import. But don't be afraid, these are only local changes, nothing has been committed.

But I want a version of the ODT plugin in which I can use the selector `screen` or `print` and both works as it should. This is not the case, I think I have to write some more test cases to get to the bottom of this.

**Comment by selfthinker** [comment]
Oh, somehow I thought there was a new release of the ODT plugin recently... Just tested with the version that is on dokuwiki.org (so, 2015-05-09 and **not master**) and that is broken with the Wrap plugin right now.
I will just add a note that it will be supported with the next release of the ODT plugin and is not supported yet.

**Pull request closed without merging**
