### PR TITLE
Fixed broken ODT export for columns if 'group' is not in 'noPrefix'

### PR DESCRIPTION
**Pull request by LarsGit223**
Added optional parameter ```$ignoreNoPrefix``` to function ```getAttributes()```. In this way the ODT helper can query all wrap classes with prefix independent of the config setting ```noPrefix```. If the parameter is omitted, the function will behave like before this commit/PR.

### CODE REVIEW

**Comment by selfthinker** [comment]
Sorry, I just merged #151 which caused conflicts in this branch. Can you please resolve them?

Wouldn't it make more sense to just allow both `group` and `wrap_group`?
I guess the most ideal solution would be to allow having no `group` at all. But I'm not sure if that's possible?

**Comment by LarsGit223** [comment]
> Sorry, I just merged #151 which caused conflicts in this branch. Can you please resolve them?

Sure, will do it as I got time for it.

> Wouldn't it make more sense to just allow both group and wrap_group?
> I guess the most ideal solution would be to allow having no group at all. But I'm not sure if that's possible?

No, I need the group to close the table which "emulates" the divs for the columns. I don't want to try frames. I think the result will not be that good.

I cannot judge the risk of only checking for group and wrap_group. How likely is it that e.g. boxes or other classes are added to ```noPrefix```? The way I solved it now simply makes sure that no other problems can arise with ```noPrefix``` in the future.

**Comment by selfthinker** [comment]
Thanks. I merged this manually to a) get rid of the merge commit and b) I also simplified the change in 9e56405783bba79d777b280e170300d50ce88c67.

**Comment by LarsGit223** [comment]
:thumbsup:  Great, thanks.

**Pull request closed without merging**
