### PR TITLE
Translation update (nl)

### PR DESCRIPTION
**Pull request by dokuwiki-translate**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by Klap-in** [comment]
Hi Anika,
Is it feasible to have a look at the open pull requests for translations?
Thanks in advance!

**Comment by Klap-in** [comment]
@selfthinker Do you have maybe an opportunity to have a look in to all the submitted translations? The wrap plugin is quite popular and high ranked in the Translation tool, but I'm afraid that the effort of merging them, will increase with the time you wait...

**Comment by selfthinker** [comment]
@Klap-in, I'm not really maintaining my DokuWiki extensions anymore. (I haven't worked on them for years, I only did a little bit this month.) The last time I asked if anyone wants to take over or help maintaining them, no-one came forward, unfortunately.
Sorry, I really don't have the capacity to work on these most of the time.
Would you be interested in helping out?

**Comment by Klap-in** [comment]
It is fine for me to perform small maintenance tasks. However, I will not do big things. To set the expectations, I will handle it similar as @dokufreaks organization.

**Comment by selfthinker** [comment]
@Klap-in, just dealing with the translations would already be a big help. I'll give you access.

The Wrap plugin is the only one to which I would like to come back to some day. I might work a bit on it soon.

**Comment by Klap-in** [comment]
@selfthinker thank you! The first PRs are merged :-) 
There seems an issue with the unit tests.. let’s see if there are general improvements possible there.

**Comment by selfthinker** [comment]
@Klap-in, thank you very much! 👍 That looks good.

**Pull request merged**
