### PR TITLE
Fix issue #272: PHP 8+ warnings, "undefined array key", margins

### PR DESCRIPTION
**Pull request by nerun**
An alternative fix for issue #272, since PR #274 Fix ODT exporting tables do not pass the tests. Crossing fingers...

I am using this fix since 22 sep 2023 and no issues.

### CODE REVIEW

**Comment by nerun** [comment]
Failed in the exactly same tests than #274.

**Comment by eduardomozart** [comment]
The ending results will be exactly as PR #274 because the margin values will be override to "0cm" since line 709 ( https://github.com/selfthinker/dokuwiki_plugin_wrap/blob/master/helper.php#L709 ). Let's wait Klap-in (I'll not mark him as he is occupied) review our code changes and he chooses the one that will be commited to the code. Thank you for your code contribution.

**Comment by nerun** [comment]
Thanks for trying friend!

**Comment by eduardomozart** [comment]
The ODT XML specification requires to specify the unit ('cm', etc.). Try avoid focusing in those auto PHP tests. I believe they are broken, maybe some required file is missing for them.

**Comment by Klap-in** [comment]
Hi, thanks for the proposals. I have not the time dive in the odt part, so may I ask you both to conclude on this topic what is the best. If following the odt specification is better then #274 is the way, otherwise #275?
If it is tested, I can merge the preferred PR.

If unit tests are incorrect, is it possible to fix them?

**Comment by eduardomozart** [comment]
Hello @Klap-in,
My PR seems to be less disruptive because it keeps the defaults value (0cm) for margin as expected from ODT XHTML specs, and I already worked on ODT plugin to migrate it to PHP 8, but both commit are good and will have the same results.
About the tests: it seems broken on Master because @splitbrain replaced the legacy PHPUnit tests on  the master branch at Sep 18, 2023 (https://github.com/dokuwiki/dokuwiki/commits/master/_test) to use composer (actually, the Wrap plugin still require the file "fetchphpunit" file): https://github.com/selfthinker/dokuwiki_plugin_wrap/blob/9c6c948e33d880fdf9583545439af9e3c1fabae4/.github/workflows/phpTestLinux.yml#L44), but I'm not sure how to migrate Wrap tests to use it.

**Comment by Klap-in** [comment]
I will see if I can add the new test setup with the dev plugin.

**Comment by nerun** [comment]
#275 was tested for one month without issues, but I DO BELIEVE #274 will work the same way. It's up to you.

**Pull request closed without merging**
